# SVD&PCA
https://stats.stackexchange.com/questions/134282/relationship-between-svd-and-pca-how-to-use-svd-to-perform-pca
https://photos.app.goo.gl/6rMaqBdnXjDWavHr6

In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
cur_dir = os.getcwd()
path = os.path.join(cur_dir,'dataset','train.csv')
path

'/data1/home/feynman52/ntu-ml/hw5/dataset/train.csv'

In [3]:
df_train = pd.read_csv( os.path.join(cur_dir,'dataset','train.csv'), sep=',' )
df_movies = pd.read_csv( os.path.join(cur_dir,'dataset','movies.csv'), sep='::' )
df_users = pd.read_csv( os.path.join(cur_dir,'dataset','users.csv'), sep='::' )
df_test = pd.read_csv( os.path.join(cur_dir,'dataset','test.csv'), sep=',' )
df_SampleSubmisson = pd.read_csv( os.path.join(cur_dir,'dataset','SampleSubmisson.csv'), sep=',' )

/data1/home/feynman52/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

/data1/home/feynman52/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

In [49]:
mean = df_train.Rating.mean()
std = df_train.Rating.std()
df_train['Rating_normalized'] = (df_train['Rating'] - mean)/std
mean
std
df_train.Rating_normalized.mean()
df_train.Rating_normalized.std()
df_train

,TrainDataID,UserID,MovieID,Rating,Rating_normalized,user_index,movie_index
0,1,796,1193,5,1.269845,795,1104
1,2,796,661,3,-0.520828,795,639
2,3,796,914,3,-0.520828,795,853
3,4,796,3408,4,0.374509,795,3177
4,5,796,2355,5,1.269845,795,2162
5,6,796,1197,3,-0.520828,795,1107
6,7,796,1287,5,1.269845,795,1195
7,8,796,2804,5,1.269845,795,2599
8,9,796,919,4,0.374509,795,858
9,10,796,595,5,1.269845,795,581
10,11,796,938,4,0.374509,795,877
11,12,796,2398,4,0.374509,795,2205
12,13,796,2918,4,0.374509,795,2710
13,14,796,1035,5,1.269845,795,970
14,15,796,2791,4,0.374509,795,2586
15,16,796,2687,3,-0.520828,795,2483
16,17,796,2018,4,0.374509,795,1838
17,18,796,3105,5,1.269845,795,2889
18,19,796,2797,4,0.374509,795,2592
19,20,796,2321,3,-0.520828,795,2128
20,21,796,720,3,-0.520828,795,689
21,22,796,527,5,1.269845,795,513
22,23,796,2340,3,-0.520828,795,2147
23,24,796,48,5,1.269845,795,47
24,25,796,1097,4,0.374509,795,1025
25,26,796,1721,4,0.374509,795,1574
26,27,796,1545,4,0.374509,795,1421
27,28,796,745,3,-0.520828,795,708
28,29,796,2294,4,0.374509,795,2102
29,30,796,3186,4,0.374509,795,2969
...,...,...,...,...,...,...,...
899843,899844,2683,3703,4,0.374509,2682,3461
899844,899845,2683,2762,4,0.374509,2682,2557
899845,899846,2683,1036,3,-0.520828,2682,971
899846,899847,2683,508,4,0.374509,2682,494
899847,899848,2683,1041,4,0.374509,2682,976
899848,899849,2683,3735,4,0.374509,2682,3493
899849,899850,2683,2791,4,0.374509,2682,2586
899850,899851,2683,2794,1,-2.311502,2682,2589
899851,899852,2683,527,5,1.269845,2682,513
899852,899853,2683,2003,1,-2.311502,2682,1823
899853,899854,2683,535,4,0.374509,2682,521
899854,899855,2683,2010,5,1.269845,2682,1830
899855,899856,2683,2011,4,0.374509,2682,1831
899856,899857,2683,3751,4,0.374509,2682,3508
899857,899858,2683,2019,5,1.269845,2682,1839
899858,899859,2683,541,4,0.374509,2682,527
899859,899860,2683,1077,5,1.269845,2682,1005
899860,899861,2683,1079,2,-1.416165,2682,1007
899861,899862,2683,549,4,0.374509,2682,535
899862,899863,2683,2020,3,-0.520828,2682,1840
899863,899864,2683,2021,3,-0.520828,2682,1841
899864,899865,2683,2022,5,1.269845,2682,1842
899865,899866,2683,2028,5,1.269845,2682,1848
899866,899867,2683,1080,4,0.374509,2682,1008
899867,899868,2683,1089,4,0.374509,2682,1017
899868,899869,2683,1090,3,-0.520828,2682,1018
899869,899870,2683,1091,1,-2.311502,2682,1019
899870,899871,2683,1094,5,1.269845,2682,1022
899871,899872,2683,562,5,1.269845,2682,548
899872,899873,2683,1097,4,0.374509,2682,1025

In [5]:
df_movies

,movieID,Title,Genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Animation|Children's
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Drama|Thriller
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Thriller
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action
20,21,Get Shorty (1995),Action|Comedy|Drama
21,22,Copycat (1995),Crime|Drama|Thriller
22,23,Assassins (1995),Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Drama
27,28,Persuasion (1995),Romance
28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama
...,...,...,...
3853,3923,Return of the Fly (1959),Horror|Sci-Fi
3854,3924,Pajama Party (1964),Comedy
3855,3925,Stranger Than Paradise (1984),Comedy
3856,3926,Voyage to the Bottom of the Sea (1961),Adventure|Sci-Fi
3857,3927,Fantastic Voyage (1966),Adventure|Sci-Fi
3858,3928,Abbott and Costello Meet Frankenstein (1948),Comedy|Horror
3859,3929,"Bank Dick, The (1940)",Comedy
3860,3930,"Creature From the Black Lagoon, The (1954)",Horror
3861,3931,"Giant Gila Monster, The (1959)",Horror|Sci-Fi
3862,3932,"Invisible Man, The (1933)",Horror|Sci-Fi
3863,3933,"Killer Shrews, The (1959)",Horror|Sci-Fi
3864,3934,Kronos (1957),Sci-Fi
3865,3935,Kronos (1973),Horror
3866,3936,"Phantom of the Opera, The (1943)",Drama|Thriller
3867,3937,Runaway (1984),Sci-Fi|Thriller
3868,3938,"Slumber Party Massacre, The (1982)",Horror
3869,3939,"Slumber Party Massacre II, The (1987)",Horror
3870,3940,"Slumber Party Massacre III, The (1990)",Horror
3871,3941,Sorority House Massacre (1986),Horror
3872,3942,Sorority House Massacre II (1990),Horror
3873,3943,Bamboozled (2000),Comedy
3874,3944,Bootmen (2000),Comedy|Drama
3875,3945,Digimon: The Movie (2000),Adventure|Animation|Children's
3876,3946,Get Carter (2000),Action|Drama|Thriller
3877,3947,Get Carter (1971),Thriller
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [6]:
df_users

      UserID Gender  Age  Occupation Zip-code
0        796      F    1          10    48067
1       3203      M   56          16    70072
2       4387      M   25          15    55117
3       4771      M   45           7    02460
4       1191      M   25          20    55455
5       2868      F   50           9    55117
6       1070      M   35           1    06810
7       5074      M   25          12    11413
8       5585      M   25          17    61614
9       3402      F   35           1    95370
10      5500      F   25           1    04093
11      1313      M   25          12    32793
12       329      M   45           1    93304
13      4145      M   35           0    60126
14      5815      M   25           7    22903
15        57      F   35           0    20670
16      3531      M   50           1    95350
17      1726      F   18           3    95825
18      2287      M    1          10    48073
19      3367      M   25          14    55113
20      4513      M   18          16    99353
21       502      M   18          15    53706
22       255      M   35           0    90049
23       417      F   25           7    10023
24      2894      M   18           4    01609
25       791      M   25           7    23112
26      3738      M   25          11    19130
27      4988      F   25           1    14607
28      4681      M   35           7    33407
29      3781      F   35           7    19143
...      ...    ...  ...         ...      ...
6010    5263      M   35          15    80538
6011    1011      M   35          15    02871
6012     238      F   25          20    32301
6013    2668      M   45           1    80634
6014    2888      F   25           9    80013
6015    5356      M   45           1    37209
6016    1839      F   35           7    21117
6017    2341      M   35           1    48906
6018    4400      M   25           0    10024
6019    4927      M   50          16    10023
6020    3731      M   25          12    08876
6021    1876      M   25          17    57006
6022    2032      M   25           0    43213
6023    2165      M   25          12    53705
6024    1680      F   25           1    32607
6025    4561      M   35           6    11210
6026    1424      M   18           4    20742
6027    1204      M   18           4    94133
6028    1152      F   25           1    23185
6029    5457      M   25          17    32618
6030    5471      F   18           0    45123
6031    5738      M   45           7    55108
6032    4151      M   50          13    78232
6033    5964      M   25          14    94117
6034    2737      F   25           1    78734
6035     259      F   25          15    32603
6036    1719      F   45           1    76006
6037    3422      F   56           1    14706
6038    2559      F   45           0    01060
6039    2683      M   25           6    11106

[6040 rows x 5 columns]

In [7]:
df_test

        TestDataID  UserID  MovieID
0                1     796      594
1                2     796     1270
2                3     796     1907
3                4    3203     2126
4                5    3203      292
5                6    3203     1188
6                7    3203      110
7                8    3203     2278
8                9    3203     1442
9               10    3203       95
10              11    3203     2571
11              12    3203     1917
12              13    3203     3809
13              14    3203     2321
14              15    3203     1527
15              16    3203     3418
16              17    3203     3678
17              18    4387      733
18              19    4387     2115
19              20    4387     2081
20              21    4771     1210
21              22    4771     2692
22              23    1191     1175
23              24    1191     2770
24              25    1191     1759
25              26    1191     3793
26              27    1191       41
27              28    1191      515
28              29    1191      377
29              30    1191     2355
...            ...     ...      ...
100306      100307    2683     2872
100307      100308    2683     2134
100308      100309    2683      300
100309      100310    2683     3521
100310      100311    2683     1921
100311      100312    2683     2599
100312      100313    2683     3543
100313      100314    2683     1960
100314      100315    2683     1975
100315      100316    2683     1200
100316      100317    2683     1240
100317      100318    2683     1251
100318      100319    2683      720
100319      100320    2683     1263
100320      100321    2683     1265
100321      100322    2683      750
100322      100323    2683     2612
100323      100324    2683     1674
100324      100325    2683     2641
100325      100326    2683     2645
100326      100327    2683     1307
100327      100328    2683      495
100328      100329    2683     2303
100329      100330    2683     1392
100330      100331    2683     2366
100331      100332    2683      111
100332      100333    2683     3334
100333      100334    2683     2717
100334      100335    2683     1784
100335      100336    2683     1096

[100336 rows x 3 columns]

# find all user 
# find all movie

In [8]:
all_user = np.concatenate([df_train.UserID,df_test.UserID],axis=0)
all_movie = np.concatenate([df_train.MovieID,df_test.MovieID],axis=0)
print(all_user.shape)
print(all_movie.shape)
all_user = np.unique(all_user)
all_movie = np.unique(all_movie)
print(all_user.shape)
print(all_movie.shape)

(1000209,)
(1000209,)
(6040,)
(3706,)

In [9]:
df_all_movie = pd.DataFrame({'movie_id':all_movie})
df_all_movie['movie_index'] = df_all_movie.index
df_all_movie

      movie_id  movie_index
0            1            0
1            2            1
2            3            2
3            4            3
4            5            4
5            6            5
6            7            6
7            8            7
8            9            8
9           10            9
10          11           10
11          12           11
12          13           12
13          14           13
14          15           14
15          16           15
16          17           16
17          18           17
18          19           18
19          20           19
20          21           20
21          22           21
22          23           22
23          24           23
24          25           24
25          26           25
26          27           26
27          28           27
28          29           28
29          30           29
...        ...          ...
3676      3923         3676
3677      3924         3677
3678      3925         3678
3679      3926         3679
3680      3927         3680
3681      3928         3681
3682      3929         3682
3683      3930         3683
3684      3931         3684
3685      3932         3685
3686      3933         3686
3687      3934         3687
3688      3935         3688
3689      3936         3689
3690      3937         3690
3691      3938         3691
3692      3939         3692
3693      3940         3693
3694      3941         3694
3695      3942         3695
3696      3943         3696
3697      3944         3697
3698      3945         3698
3699      3946         3699
3700      3947         3700
3701      3948         3701
3702      3949         3702
3703      3950         3703
3704      3951         3704
3705      3952         3705

[3706 rows x 2 columns]

In [10]:
df_all_user = pd.DataFrame({'user_id':all_user})
df_all_user['user_index'] = df_all_user.index
df_all_user

      user_id  user_index
0           1           0
1           2           1
2           3           2
3           4           3
4           5           4
5           6           5
6           7           6
7           8           7
8           9           8
9          10           9
10         11          10
11         12          11
12         13          12
13         14          13
14         15          14
15         16          15
16         17          16
17         18          17
18         19          18
19         20          19
20         21          20
21         22          21
22         23          22
23         24          23
24         25          24
25         26          25
26         27          26
27         28          27
28         29          28
29         30          29
...       ...         ...
6010     6011        6010
6011     6012        6011
6012     6013        6012
6013     6014        6013
6014     6015        6014
6015     6016        6015
6016     6017        6016
6017     6018        6017
6018     6019        6018
6019     6020        6019
6020     6021        6020
6021     6022        6021
6022     6023        6022
6023     6024        6023
6024     6025        6024
6025     6026        6025
6026     6027        6026
6027     6028        6027
6028     6029        6028
6029     6030        6029
6030     6031        6030
6031     6032        6031
6032     6033        6032
6033     6034        6033
6034     6035        6034
6035     6036        6035
6036     6037        6036
6037     6038        6037
6038     6039        6038
6039     6040        6039

[6040 rows x 2 columns]

In [11]:
movie_id_to_index = df_all_movie.set_index('movie_id').to_dict()
movie_id_to_index = movie_id_to_index['movie_index']
user_id_to_index = df_all_user.set_index('user_id').to_dict()
user_id_to_index = user_id_to_index['user_index']
movie_id_to_index[3952]

3705

In [12]:
df_train['user_index'] =  df_train.apply(lambda row: user_id_to_index[row.UserID] ,axis=1)
df_train['movie_index'] =  df_train.apply(lambda row: movie_id_to_index[row.MovieID] ,axis=1)

df_train

,TrainDataID,UserID,MovieID,Rating,Rating_normalized,user_index,movie_index
0,1,796,1193,5,1.418288,795,1104
1,2,796,661,3,-0.581712,795,639
2,3,796,914,3,-0.581712,795,853
3,4,796,3408,4,0.418288,795,3177
4,5,796,2355,5,1.418288,795,2162
5,6,796,1197,3,-0.581712,795,1107
6,7,796,1287,5,1.418288,795,1195
7,8,796,2804,5,1.418288,795,2599
8,9,796,919,4,0.418288,795,858
9,10,796,595,5,1.418288,795,581
10,11,796,938,4,0.418288,795,877
11,12,796,2398,4,0.418288,795,2205
12,13,796,2918,4,0.418288,795,2710
13,14,796,1035,5,1.418288,795,970
14,15,796,2791,4,0.418288,795,2586
15,16,796,2687,3,-0.581712,795,2483
16,17,796,2018,4,0.418288,795,1838
17,18,796,3105,5,1.418288,795,2889
18,19,796,2797,4,0.418288,795,2592
19,20,796,2321,3,-0.581712,795,2128
20,21,796,720,3,-0.581712,795,689
21,22,796,527,5,1.418288,795,513
22,23,796,2340,3,-0.581712,795,2147
23,24,796,48,5,1.418288,795,47
24,25,796,1097,4,0.418288,795,1025
25,26,796,1721,4,0.418288,795,1574
26,27,796,1545,4,0.418288,795,1421
27,28,796,745,3,-0.581712,795,708
28,29,796,2294,4,0.418288,795,2102
29,30,796,3186,4,0.418288,795,2969
...,...,...,...,...,...,...,...
899843,899844,2683,3703,4,0.418288,2682,3461
899844,899845,2683,2762,4,0.418288,2682,2557
899845,899846,2683,1036,3,-0.581712,2682,971
899846,899847,2683,508,4,0.418288,2682,494
899847,899848,2683,1041,4,0.418288,2682,976
899848,899849,2683,3735,4,0.418288,2682,3493
899849,899850,2683,2791,4,0.418288,2682,2586
899850,899851,2683,2794,1,-2.581712,2682,2589
899851,899852,2683,527,5,1.418288,2682,513
899852,899853,2683,2003,1,-2.581712,2682,1823
899853,899854,2683,535,4,0.418288,2682,521
899854,899855,2683,2010,5,1.418288,2682,1830
899855,899856,2683,2011,4,0.418288,2682,1831
899856,899857,2683,3751,4,0.418288,2682,3508
899857,899858,2683,2019,5,1.418288,2682,1839
899858,899859,2683,541,4,0.418288,2682,527
899859,899860,2683,1077,5,1.418288,2682,1005
899860,899861,2683,1079,2,-1.581712,2682,1007
899861,899862,2683,549,4,0.418288,2682,535
899862,899863,2683,2020,3,-0.581712,2682,1840
899863,899864,2683,2021,3,-0.581712,2682,1841
899864,899865,2683,2022,5,1.418288,2682,1842
899865,899866,2683,2028,5,1.418288,2682,1848
899866,899867,2683,1080,4,0.418288,2682,1008
899867,899868,2683,1089,4,0.418288,2682,1017
899868,899869,2683,1090,3,-0.581712,2682,1018
899869,899870,2683,1091,1,-2.581712,2682,1019
899870,899871,2683,1094,5,1.418288,2682,1022
899871,899872,2683,562,5,1.418288,2682,548
899872,899873,2683,1097,4,0.418288,2682,1025

In [13]:
user_train = df_train.user_index
movie_train = df_train.movie_index
rating_train = df_train.Rating

In [14]:
rating_train.shape

(899873,)

In [50]:
n_users= len(user_train)
n_movies= len(movie_train)
latent_dim=20

In [51]:
# np.clip([0,1,2,5,6],1,5)
np.power([2,3], 3)

array([ 8, 27])

# w/o normalize

In [44]:
from keras.layers import Input, Dense, Embedding, Flatten, dot
from keras.models import Model
from keras.utils import get_custom_objects
import keras.backend as K

user_input = Input(shape=(1,))
movie_input = Input(shape=(1,))

user_vecter = Embedding(n_users, latent_dim, embeddings_initializer="random_normal")(user_input)
user_vecter = Flatten()(user_vecter)

movie_vecter = Embedding(n_movies, latent_dim, embeddings_initializer="random_normal")(movie_input)
movie_vecter = Flatten()(movie_vecter)


rating_predict = dot([user_vecter,movie_vecter],axes=1)

model = Model([user_input,movie_input],rating_predict)



def rmse(y_true, y_pred):
    y_pred = K.clip(y_pred, 1.0, 5.0)
    return K.sqrt(K.mean(K.pow(y_true - y_pred, 2)))
get_custom_objects().update({"rmse": rmse})

model.compile(loss="mse", optimizer="adam", metrics=[rmse])

model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_9 (InputLayer)            (None, 1)            0
__________________________________________________________________________________________________
input_10 (InputLayer)           (None, 1)            0
__________________________________________________________________________________________________
embedding_9 (Embedding)         (None, 1, 20)        17997460    input_9[0][0]
__________________________________________________________________________________________________
embedding_10 (Embedding)        (None, 1, 20)        17997460    input_10[0][0]
__________________________________________________________________________________________________
flatten_9 (Flatten)             (None, 20)           0           embedding_9[0][0]
__________________________________________________________________________________________________
flatten_10 (Flatten)            (None, 20)           0           embedding_10[0][0]
__________________________________________________________________________________________________
dot_5 (Dot)                     (None, 1)            0           flatten_9[0][0]
                                                                 flatten_10[0][0]
==================================================================================================
Total params: 35,994,920
Trainable params: 35,994,920
Non-trainable params: 0
__________________________________________________________________________________________________

In [45]:
batch_size=256
epochs = 10

# why shuffle?
# https://keras-cn.readthedocs.io/en/latest/for_beginners/trap/#shufflevalidation_split
user_train2, movie_train2, rating_train2 = shuffle(user_train, movie_train, rating_train)


hitsory = model.fit([user_train2, movie_train2],
                    rating_train2,
                    batch_size=batch_size,
                    epochs=epochs,
                    validation_split=0.1,
                    shuffle=True)

Train on 809885 samples, validate on 89988 samples
Epoch 1/10
809885/809885 [==============================] - 61s 75us/step - loss: 6.4979 - rmse: 1.9831 - val_loss: 1.1560 - val_rmse: 1.0688
Epoch 2/10
809885/809885 [==============================] - 61s 75us/step - loss: 0.9330 - rmse: 0.9619 - val_loss: 0.8561 - val_rmse: 0.9225
Epoch 3/10
809885/809885 [==============================] - 60s 75us/step - loss: 0.8206 - rmse: 0.9038 - val_loss: 0.8220 - val_rmse: 0.9043
Epoch 4/10
809885/809885 [==============================] - 60s 74us/step - loss: 0.7951 - rmse: 0.8900 - val_loss: 0.8087 - val_rmse: 0.8972
Epoch 5/10
809885/809885 [==============================] - 60s 75us/step - loss: 0.7785 - rmse: 0.8807 - val_loss: 0.7978 - val_rmse: 0.8911
Epoch 6/10
809885/809885 [==============================] - 60s 74us/step - loss: 0.7255 - rmse: 0.8502 - val_loss: 0.7727 - val_rmse: 0.8770
Epoch 9/10
809885/809885 [==============================] - 60s 75us/step - loss: 0.7048 - rmse: 0.8380 - val_loss: 0.7631 - val_rmse: 0.8713
Epoch 10/10
809885/809885 [==============================] - 60s 74us/step - loss: 0.6838 - rmse: 0.8252 - val_loss: 0.7611 - val_rmse: 0.8701

# w/i normalize

In [ ]:
from keras.layers import Input, Dense, Embedding, Flatten, dot
from keras.models import Model
from keras.utils import get_custom_objects
import keras.backend as K

user_input = Input(shape=(1,))
movie_input = Input(shape=(1,))

user_vecter = Embedding(n_users, latent_dim, embeddings_initializer="random_normal")(user_input)
user_vecter = Flatten()(user_vecter)

movie_vecter = Embedding(n_movies, latent_dim, embeddings_initializer="random_normal")(movie_input)
movie_vecter = Flatten()(movie_vecter)


rating_predict = dot([user_vecter,movie_vecter],axes=1)

model = Model([user_input,movie_input],rating_predict)



def rmse(y_true, y_pred):
    y_true = y_true*std+mean
    y_pred = y_pred*std+mean
    y_pred = K.clip(y_pred, 1.0, 5.0)
    return K.sqrt(K.mean(K.pow(y_true - y_pred, 2)))
get_custom_objects().update({"rmse": rmse})

model.compile(loss="mse", optimizer="adam", metrics=[rmse])

model.summary()

3.5817120860388076